name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  cypress-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm test
        continue-on-error: true

      - name: Set datetime for artifact
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Upload all reports (if exists)
        if: always() && hashFiles('cypress/reports/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-${{ github.run_number }}-${{ steps.datetime.outputs.datetime }}
          path: cypress/reports
          retention-days: 2
